## Q6: Conway's Game of Life

All the functions are in the game_of_life_funcs.py file, here I just import and execute them

In [9]:
#make sure my import of the functions i wrote is up to date with the changes I make to the .py file
import game_of_life_funcs as f
import importlib
importlib.reload(f)

import numpy as np

#generate a 2D grid with random 0s and 1s, maybe we can also try to work on some configuration thaat will make the game go on for longer
#but that's a problem for later

generator = np.random.default_rng()
my_grid = generator.integers(low = 0, high=1, endpoint = True, size = (10,10))
f.play_life_game(my_grid, 3)

initial state: 
 [[1 0 0 0 1 0 1 0 0 1]
 [0 0 1 1 1 1 0 0 1 1]
 [1 0 0 0 0 1 0 1 1 1]
 [1 0 1 1 0 1 1 1 0 0]
 [0 1 1 0 0 0 1 1 1 0]
 [1 1 0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1 1 1]
 [0 1 0 0 0 0 1 1 1 0]
 [0 0 1 1 0 1 1 0 1 1]
 [0 0 1 1 0 1 0 0 0 0]]
i = 1 ,
 [[0 0 0 1 1 0 0 0 0 1]
 [0 0 0 1 1 1 1 0 1 0]
 [0 0 0 1 1 1 0 1 0 1]
 [0 1 1 1 0 1 1 0 0 0]
 [1 1 1 1 0 0 1 1 0 0]
 [1 1 1 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 1 0 1]
 [0 0 0 0 0 0 1 0 1 0]
 [0 0 1 1 1 1 1 1 1 0]
 [0 0 1 1 0 0 0 0 0 0]]
i = 2 ,
 [[0 0 0 1 1 1 0 0 0 0]
 [0 0 0 1 0 0 1 1 0 1]
 [0 0 1 0 0 1 0 0 1 0]
 [0 1 0 0 0 1 1 0 0 0]
 [1 0 0 1 0 0 1 0 0 0]
 [1 0 1 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 1 1]
 [0 0 1 0 1 1 1 1 1 0]
 [0 0 1 1 0 0 0 0 0 0]]
i = 3 ,
 [[0 0 0 1 1 0 0 0 0 0]
 [0 0 0 1 0 1 1 0 1 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 1 1]
 [0 0 0 0 1 1 1 1 1 0]
 [0 0 1 0 0 0 0 0 0 0]]
