## Q6: Conway's Game of Life

All the functions are in the game_of_life_funcs.py file, here I just import and execute them

In [ ]:
import game_of_life_funcs as f
import importlib
importlib.reload(f)
import numpy as np

# generate a 2D grid with random 0s and 1s, maybe we can also try to work on some configuration that will make the game go on for longer

# the function takes as arguments the initial grid and number of iterations the user wants

generator = np.random.default_rng(0)
my_grid = (generator.random((50, 50)) < 0.30).astype(int)  # ~30% alive - 50% population dies too fast
gridlist = f.play_life_game(my_grid, 3)

initial state: 
 [[0 1 1 ... 0 1 0]
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [1 0 1 ... 1 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]
i = 1 ,
 [[1 1 0 ... 1 0 0]
 [1 1 0 ... 0 0 0]
 [1 1 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [1 1 0 ... 1 0 0]]
i = 2 ,
 [[0 0 0 ... 1 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 1 0 1]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [0 0 0 ... 1 0 1]]
i = 3 ,
 [[1 0 1 ... 0 0 1]
 [1 0 0 ... 0 0 1]
 [1 0 0 ... 1 0 1]
 ...
 [1 0 0 ... 0 0 1]
 [1 1 0 ... 0 0 1]
 [1 0 1 ... 0 0 1]]
i = 4 ,
 [[0 0 1 ... 0 1 0]
 [0 0 1 ... 0 0 0]
 [1 0 0 ... 0 1 1]
 ...
 [0 1 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 [0 0 1 ... 0 1 0]]
i = 5 ,
 [[0 1 0 ... 1 0 0]
 [0 1 0 ... 1 1 0]
 [1 0 0 ... 0 0 1]
 ...
 [0 0 1 ... 1 0 1]
 [0 0 0 ... 0 1 1]
 [0 0 1 ... 1 1 1]]
i = 6 ,
 [[1 1 0 ... 0 0 1]
 [0 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [0 0 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [1 0 1 ... 1 0 1]]
i = 7 ,
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]

play it but animated version - its saved in a gif file in the local dir

In [6]:
generator = np.random.default_rng(0)
my_grid = (generator.random((50, 50)) < 0.30).astype(int)  
animation = f.play_life_game_wplots(my_grid, 300)
animation.save( "life_game.gif", writer="ffmpeg", fps=20)

MovieWriter ffmpeg unavailable; using Pillow instead.
